name: Nightly Smoke Tests

on:
  # Trigger manually or on schedule
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  smoke:
    name: Nightly Smoke Test
    strategy:
      fail-fast: false
      matrix:
        dotnet_version: ['6.0.300', '7.0.x']
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    env:
      NX_RUN_GROUP: ${{ github.run_id }}-v${{matrix.dotnet_version}}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{matrix.dotnet_version}}
          include-prerelease: true
      - uses: bahmutov/npm-install@v1.4.5
      - run: yarn nx run-many --all --target=smoke
